### ISSUE TITLE
world floor, roof, walls and color of the crowd

### ISSUE THREAD

**Issue by HagaiAS** [HagaiAS/BoxingOpenGL#14]
color the crowd randomly and color the roof walls floor

**Comment by HarelEzra** [comment]
צבע הקהל שונה מאחד לשני, בינתיים כל הקופסא של העולם בצבע אחיד, בהמשך נצייר את הקופסא מחלקים שונים כדי לצבוע קירות ורצפה בצבעים שונים

**Comment by HarelEzra** [comment]
לתקן עם טקסטורה ובנוסף ליצור את הקוביה מ-6 vertex  ולא כ-cube יחיד

**Comment by HarelEzra** [comment]
הקהל בצבעים שונים, הרצפה מחולקת למרצפות והקירות בטקסטורה
